language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'cd(Pkg.dir("WeakRefStrings")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
